// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCc4JTRICyvc4bnVXOLdtxXXFuGPZoaX8',
    appId: '1:784679121752:web:fe53aa37c2bfec504e2b2d',
    messagingSenderId: '784679121752',
    projectId: 'learning-firebase-again-2',
    authDomain: 'learning-firebase-again-2.firebaseapp.com',
    storageBucket: 'learning-firebase-again-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHTv63OoQ4Q0w9UslsTOwDfOgnAhjtiys',
    appId: '1:784679121752:android:beb7f3a7f1ea85064e2b2d',
    messagingSenderId: '784679121752',
    projectId: 'learning-firebase-again-2',
    storageBucket: 'learning-firebase-again-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJThX1MWNGFI2gXTQ1SSzDjcPhbixnaE',
    appId: '1:784679121752:ios:52a2a044ac9755104e2b2d',
    messagingSenderId: '784679121752',
    projectId: 'learning-firebase-again-2',
    storageBucket: 'learning-firebase-again-2.firebasestorage.app',
    iosBundleId: 'com.sample.learningfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJThX1MWNGFI2gXTQ1SSzDjcPhbixnaE',
    appId: '1:784679121752:ios:52a2a044ac9755104e2b2d',
    messagingSenderId: '784679121752',
    projectId: 'learning-firebase-again-2',
    storageBucket: 'learning-firebase-again-2.firebasestorage.app',
    iosBundleId: 'com.sample.learningfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCc4JTRICyvc4bnVXOLdtxXXFuGPZoaX8',
    appId: '1:784679121752:web:6790bef9642f34644e2b2d',
    messagingSenderId: '784679121752',
    projectId: 'learning-firebase-again-2',
    authDomain: 'learning-firebase-again-2.firebaseapp.com',
    storageBucket: 'learning-firebase-again-2.firebasestorage.app',
  );

}